--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iAldrich23xX/TeleportationBlock
build-by-default: true
branches:
- main
projects:
  TeleportationBlock:
    path: ""
    icon: icon.png
    lint: false
...
